/**:
  platform:
    ros__parameters: 
      gps_origin: # GPS origin in latitude, longitude and altitude
        latitude: 40.4405287 # Latitude GPS origin. Degrees
        longitude: -3.6898277 # Longitude GPS origin. Degrees
        altitude: 100.0 # Altitude GPS origin. Meters

drone0:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: -1.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.2 # Initial z position of the vehicle in odometry frame. Meters

drone1:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 1.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.2 # Initial z position of the vehicle in odometry frame. Meters

drone2:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 0.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.2 # Initial z position of the vehicle in odometry frame. Meters

drone3:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: 1.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.2 # Initial z position of the vehicle in odometry frame. Meters

drone4:
  platform:
    ros__parameters: 
      vehicle_initial_pose:
        x: 0.0 # Initial x position of the vehicle in odometry frame. Meters
        y: -1.0 # Initial y position of the vehicle in odometry frame. Meters
        z: 0.2 # Initial z position of the vehicle in odometry frame. Meters